Proj 1 vector operations
NMar33/made-cpp-2020-hw pull request #3
Opened 2020-10-06 19:47 UTC by NMar33

2020-10-17 23:35 UTC, xterrafunny requested changes

2020-10-17 23:35 UTC, xterrafunny commented on vector_ops/src/vector_ops.h
> +vector<double> operator+ (
Пробел перед списком аргументов не нужен

2020-10-17 23:35 UTC, xterrafunny commented on vector_ops/src/vector_ops.h
> +){
Это должно быть на предыдущей строке

2020-10-17 23:35 UTC, xterrafunny commented on vector_ops/src/vector_ops.h
> +){
Нужен пробел перед фигурной скобкой

2020-10-17 23:35 UTC, xterrafunny commented on vector_ops/src/vector_ops.h
> +    vector<double> c;
Зачем заставлять вектор расширяться, если его размер известен

2020-10-17 23:35 UTC, xterrafunny commented on vector_ops/src/vector_ops.h
> +        c.push_back(a[i] );
Зачем тут пробел

2020-10-17 23:35 UTC, xterrafunny commented on vector_ops/src/vector_ops.h
> +bool check_zero (
Почитайте про названия функций в GCS

2020-10-17 23:35 UTC, xterrafunny commented on vector_ops/src/vector_ops.h
> +    return true;
Много пустых строк

2020-10-17 23:35 UTC, xterrafunny commented on vector_ops/src/vector_ops.h
> +    for(int i = 0; i < a.size(); ++ i) {
Зачем пробел после `++`

2020-10-31 22:36 UTC, SweetWeakness commented
Давно не было от вас новостей, мерджим, но баллы снимаем.

2020-10-31 22:36 UTC, merged